# Generated by Django 5.2.4 on 2025-08-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('TECHNICIAN', 'Technician'), ('ADMIN', 'Admin')], default='CLIENT', max_length=10),
        ),
    ]
