# Generated by Django 5.2.5 on 2025-08-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CLIENT', 'Client'), ('TECHNICIAN', 'Technician'), ('ADMIN', 'Admin'), ('AUDITOR', 'Auditor')], default='CLIENT', max_length=10),
        ),
    ]
