# Generated by Django 5.2.4 on 2025-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticket_created_by_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='cardholder_name',
            new_name='card_serial_number',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='fault_description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='other_category_description',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='unique_card_identifier',
        ),
        migrations.AddField(
            model_name='ticket',
            name='node_name',
            field=models.CharField(choices=[('PSS-32', 'PSS-32'), ('PSS-16II', 'PSS-16II'), ('PSS-8', 'PSS-8'), ('PSS-24X', 'PSS-24X')], default='PSS-32', max_length=100),
            preserve_default=False,
        ),
    ]
