# Generated by Django 5.2.4 on 2025-08-04 12:01

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_rename_cardholder_name_ticket_card_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=tickets.models.ticket_image_upload_path),
        ),
    ]
