# Generated by Django 5.2.4 on 2025-08-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='node_name',
            field=models.CharField(max_length=100),
        ),
    ]
