# Generated by Django 5.2.5 on 2025-08-08 21:08

from django.db import migrations
from django.db.models import F

def backfill_closed_at_data(apps, schema_editor):
    """
    Finds all existing closed tickets where closed_at is currently NULL
    and sets their closed_at timestamp to be the same as their updated_at timestamp.
    """
    Ticket = apps.get_model('tickets', 'Ticket')
    # This is the core logic:
    Ticket.objects.filter(status='CLOSED', closed_at__isnull=True).update(closed_at=F('updated_at'))
    
class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticket_closed_at'),
    ]

    operations = [
        migrations.RunPython(backfill_closed_at_data),
    ]
