# Generated by Django 5.2.5 on 2025-09-15 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_backfill_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('node_type', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('card_type', models.CharField(max_length=100)),
                ('slot', models.CharField(max_length=100)),
                ('node_name', models.CharField(max_length=100)),
                ('primary_ip', models.GenericIPAddressField()),
                ('aid', models.CharField(max_length=100)),
                ('unit_part_number', models.CharField(max_length=100)),
                ('clei', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='ba_oa',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='card_category',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='card_serial_number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='circle',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='node_location',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='node_name',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='in_progress_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='in_transit_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='on_hold_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='other_card_type_description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='under_repair_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('IN_TRANSIT', 'In Transit'), ('UNDER_REPAIR', 'Under Repair'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ON_HOLD', 'On Hold')], default='OPEN', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.card'),
        ),
    ]
