# Generated by Django 5.2.5 on 2025-10-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_activitylog_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user_role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
